apiVersion: cert-manager.io/v1
kind: ClusterIssuer # I'm using ClusterIssuer here
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: lakehouse-k8s@gmail.com
    privateKeySecretRef:
      name: letsencrypt-lakehouse-k8s
    solvers:
      - http01:
          ingress:
            class: ngrok
