apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-generator
  namespace: data
  labels:
    app: data-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-generator
  template:
    metadata:
      labels:
        app: data-generator
    spec:
      containers:
        - name: data-generator
          image: brenomiranda/data-lakehouse-data-producer:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: strimzi-kafka-brokers.strimzi.svc.cluster.local:9092
